feat:
  - title: '(?i)\[feat\]'
  - base-branch: '(?i)^feat'

refactor:
  - title: '(?i)\[refact\]'
  - base-branch: '(?i)^refactor'

perfor:
  - title: '(?i)\[perfor\]'
  - base-branch: '(?i)^perfor'

bug:
  - title: '(?i)\[bug\]'
  - base-branch: '(?i)^(bug|hotfix)'

docs:
  - title: '(?i)\[docs\]'
  - base-branch: '(?i)^docs'
  - '**/*.md'

cicd:
  - title: '(?i)\[cicd\]'
  - base-branch: '(?i)^cicd'

test:
  - title: '(?i)\[test\]'
  - base-branch: '(?i)^test'
  - '**/*Test.java'

chore:
  - title: '(?i)\[chore\]'
  - base-branch: '(?i)^chore'
  - '**/*.yml'
  - '**/*.yaml'