feat:
  - title: '(?i)\[feat\]'
  - branch: '(?i)^feat'
  - files: 'feat/**'

refactor:
  - title: '(?i)\[refact\]'
  - branch: '(?i)^refactor'
  - files: 'refactor/**'

perfor:
  - title: '(?i)\[perfor\]'
  - branch: '(?i)^perfor'
  - files: 'perfor/**'

bug:
  - title: '(?i)\[bug\]'
  - branch: '(?i)^(bug|hotfix)'
  - files: 'bug/**'

docs:
  - title: '(?i)\[docs\]'
  - branch: '(?i)^docs'
  - files: '**/*.md'

cicd:
  - title: '(?i)\[cicd\]'
  - branch: '(?i)^cicd'
  - files: 'cicd/**'

test:
  - title: '(?i)\[test\]'
  - branch: '(?i)^test'
  - files: '**/*Test.java'

chore:
  - title: '(?i)\[chore\]'
  - branch: '(?i)^chore'
  - files: |
      **/*.yml
      **/*.yaml